// Code generated by MockGen. DO NOT EDIT.
// Source: ./scaler.go

// Package scales is a generated GoMock package.
package scales

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// Mockscaler is a mock of scaler interface.
type Mockscaler struct {
	ctrl     *gomock.Controller
	recorder *MockscalerMockRecorder
}

// MockscalerMockRecorder is the mock recorder for Mockscaler.
type MockscalerMockRecorder struct {
	mock *Mockscaler
}

// NewMockscaler creates a new mock instance.
func NewMockscaler(ctrl *gomock.Controller) *Mockscaler {
	mock := &Mockscaler{ctrl: ctrl}
	mock.recorder = &MockscalerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockscaler) EXPECT() *MockscalerMockRecorder {
	return m.recorder
}

// Scale mocks base method.
func (m *Mockscaler) Scale(config ScaleConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scale", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scale indicates an expected call of Scale.
func (mr *MockscalerMockRecorder) Scale(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scale", reflect.TypeOf((*Mockscaler)(nil).Scale), config)
}

// MockscaleTypeHelperInterface is a mock of scaleTypeHelperInterface interface.
type MockscaleTypeHelperInterface struct {
	ctrl     *gomock.Controller
	recorder *MockscaleTypeHelperInterfaceMockRecorder
}

// MockscaleTypeHelperInterfaceMockRecorder is the mock recorder for MockscaleTypeHelperInterface.
type MockscaleTypeHelperInterfaceMockRecorder struct {
	mock *MockscaleTypeHelperInterface
}

// NewMockscaleTypeHelperInterface creates a new mock instance.
func NewMockscaleTypeHelperInterface(ctrl *gomock.Controller) *MockscaleTypeHelperInterface {
	mock := &MockscaleTypeHelperInterface{ctrl: ctrl}
	mock.recorder = &MockscaleTypeHelperInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscaleTypeHelperInterface) EXPECT() *MockscaleTypeHelperInterfaceMockRecorder {
	return m.recorder
}

// IdentifyHpaType mocks base method.
func (m *MockscaleTypeHelperInterface) IdentifyHpaType(scaleConfig *ScaleConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentifyHpaType", scaleConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// IdentifyHpaType indicates an expected call of IdentifyHpaType.
func (mr *MockscaleTypeHelperInterfaceMockRecorder) IdentifyHpaType(scaleConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentifyHpaType", reflect.TypeOf((*MockscaleTypeHelperInterface)(nil).IdentifyHpaType), scaleConfig)
}
