apiVersion: v1
kind: Namespace
metadata:
  name: some-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: some-api
  name: some-api
  namespace: some-api
spec:
  selector:
    matchLabels:
      app: some-api
  template:
    metadata:
      labels:
        app: some-api
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: some-api
  namespace: some-api
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: some-api
---
apiVersion: v1
kind: Namespace
metadata:
  name: some-api-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: some-api-2
  name: some-api-2
  namespace: some-api-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: some-api-2
  template:
    metadata:
      labels:
        app: some-api-2
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80