apiVersion: v1
kind: Namespace
metadata:
  name: pod-autoscaler
---
apiVersion: v1
kind: Service
metadata:
  name: pod-autoscaler
  namespace: pod-autoscaler
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8090
  selector:
    app: pod-autoscaler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-autoscaler
  namespace: pod-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-autoscaler
  template:
    metadata:
      labels:
        app: pod-autoscaler
    spec:
      serviceAccountName: pod-autoscaler-sa
      automountServiceAccountToken: true
      containers:
      - name: pod-autoscaler
        image: pliniogsnascimento/pod-autoscaler-for-tests:0.0.4-dev
        ports:
        - containerPort: 8090
      restartPolicy: Always
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-autoscaler
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-autoscaler-sa
  namespace: pod-autoscaler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-autoscaler-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-autoscaler
subjects:
- kind: ServiceAccount
  name: pod-autoscaler-sa
  namespace: pod-autoscaler
