name: Build and Test
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - uses: actions/checkout@v3
    - run: go build
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - uses: actions/checkout@v3
    - run: go test ./... -v
  build-image:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: |
        docker build . --file Dockerfile --tag pliniogsnascimento/pod-autoscaler-for-tests:latest


